/* Copyright 2018-2021 Universidad Politécnica de Madrid (UPM).
 *
 * Authors:
 *    Sara Lana Serrano
 *    Mario San Emeterio de la Parte
 *    Vicente Hernández Díaz
 *    José-Fernan Martínez Ortega
 *
 * This software is distributed under a dual-license scheme:
 *
 * - For academic uses: Licensed under GNU Affero General Public License as
 *                      published by the Free Software Foundation, either
 *                      version 3 of the License, or (at your option) any
 *                      later version.
 *
 * - For any other use: Licensed under the Apache License, Version 2.0.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * You can get a copy of the license terms in licenses/LICENSE.
 *
 */
/**

 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.afarcloud.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum EquipmentType implements org.apache.thrift.TEnum {
  CAMERA_360(0),
  CAMERA_PHOTO(1),
  CAMERA_VIDEO(2),
  IR_CAMERA_PHOTO(3),
  IR_CAMERA_VIDEO(4),
  WIFI(5),
  COLLISION_AVOIDANCE(6);

  private final int value;

  private EquipmentType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static EquipmentType findByValue(int value) { 
    switch (value) {
      case 0:
        return CAMERA_360;
      case 1:
        return CAMERA_PHOTO;
      case 2:
        return CAMERA_VIDEO;
      case 3:
        return IR_CAMERA_PHOTO;
      case 4:
        return IR_CAMERA_VIDEO;
      case 5:
        return WIFI;
      case 6:
        return COLLISION_AVOIDANCE;
      default:
        return null;
    }
  }
}
